name: Update Documentation
run-name: ${{ github.actor }} has pushed; updating documentation.
on: [push]

jobs:
  update-documentation:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Update documentation
        run: bash code/generate_documentation.sh
      - run: |
          git config user.email "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"
          git config user.name "${{ github.actor }}"
          git add .
          git commit -m "Update documentation"
          git push 